[package]
name = "doome"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "doome-engine",
    "doome-fonts",
    "doome-raytracer",
    "doome-raytracer-shader",
    "doome-raytracer-shader-builder",
    "doome-raytracer-shader-common",
    "doome-run-wasm"
]

[dependencies]
doome-engine = { path = "doome-engine" }
