[workspace]
resolver = "2"
members = [
    "doome-bevy",
    "doome-engine",
    "doome-raytracer",
    "doome-raytracer-shader",
    "doome-raytracer-shader-builder",
    "doome-raytracer-shader-common",
    "doome-run-wasm",
    "doome-surface",
    "doome-text",
]

[package]
name = "doome"
version = "0.1.0"
edition = "2021"

[dependencies]
doome-bevy = { path = "doome-bevy" }
doome-raytracer = { path = "doome-raytracer" }
doome-engine = { path = "doome-engine" }
doome-surface = { path = "doome-surface" }
doome-text = { path = "doome-text" }

bevy = { version = "0.9", default-features = false, features = ["bevy_winit"] }

glam = "0.22"
include_dir = "0.7"

[profile.dev]
overflow-checks = false
