[workspace]
resolver = "2"
members = [
    "crates/lib/*",
    "crates/bin/*",
    "crates/shaders/*",
]

[package]
name = "doome"
version = "0.1.0"
edition = "2021"

[dependencies]
doome-bevy = { path = "crates/lib/doome-bevy" }
raytracer = { path = "crates/lib/raytracer" }
engine = { path = "crates/lib/engine" }
surface = { path = "crates/lib/surface" }
text = { path = "crates/lib/text" }

bevy = { version = "0.9", default-features = false, features = ["bevy_winit"] }

glam = "0.22"
include_dir = "0.7"

[profile.dev]
overflow-checks = false
