[package]
name = "doome"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "doome-engine",
    "doome-raytracer",
    "doome-raytracer-shader",
    "doome-raytracer-shader-builder",
    "doome-raytracer-shader-common",
    "doome-run-wasm",
    "doome-surface",
    "doome-text"
]

[dependencies]
doome-engine = { path = "doome-engine" }
doome-surface = { path = "doome-surface" }
doome-text = { path = "doome-text" }

[patch."crates-io"]
wgpu-core = { git = "ssh://git@github.com/Patryk27/doome-wgpu.git" }
wgpu-hal = { git = "ssh://git@github.com/Patryk27/doome-wgpu.git" }
