extra-watch-dirs = [
    "crates/lib/shader-common"
]

[[shaders]]
source-dir = "crates/shaders/raytracer"
target-dir = "crates/lib/raytracer/src/shader"

[[shaders]]
source-dir = "crates/shaders/scaler"
target-dir = "crates/lib/scaler/src/shader"

[[shaders]]
source-dir = "crates/shaders/pixels"
target-dir = "crates/lib/pixels/src/shader"

[[shaders]]
source-dir = "crates/shaders/crt"
target-dir = "crates/lib/screen-space-effects/src/crt"

[[shaders]]
source-dir = "crates/shaders/debug"
target-dir = "crates/lib/debug-pass/src/debug-pass"
