[package]
name = "doome-raytracer-shader-common"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
spirv-std = { git = "https://github.com/EmbarkStudios/rust-gpu", features = ["glam"] }
