[package]
name = "doome-shader-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bson = "2.3"
clap = { version = "4.0", features = ["derive", "env"] }
dotenv = "0.15"
fs_extra = "1.2"
log = "0.4"
naga = { version = "0.10", features = ["spv-in", "serialize"] }
notify = "5.0"
pretty_env_logger = "0.4"
serde = { version = "1.0", features = ["derive"] }
spirv-builder = { git = "https://github.com/EmbarkStudios/rust-gpu", rev = "dcf37b75a7f9e7a94f52c8a3a5d93af795e34cd0" }
toml = "0.5"
